/**
 * Localized strings for the standalone lead-form block.
 * Mirrored shape across `uk` and `en` — keep them in lockstep when
 * adding new keys.
 */

import type { LeadFormLocale } from "@/constants/form-options";

export const LEAD_FORM_STRINGS_BY_LOCALE = {
  uk: {
    nameLabel: "Ім'я",
    namePlaceholder: "Як до вас звертатися (необовʼязково)",
    namePlaceholderShort: "Необовʼязково",
    contactLabel: "Телефон, Telegram або email",
    contactPlaceholder: "+380..., @username або hello@example.com",
    contactPlaceholderShort: "+380..., @username або email",
    contactDescription: "Відповімо туди, де вам зручно",
    contactValidation: "Вкажіть телефон, Telegram або email",
    tierLabel: "Що потрібно",
    tierPlaceholder: "Оберіть",
    budgetLabel: "Бюджет",
    budgetPlaceholder: "Оберіть діапазон",
    budgetValidation: "Оберіть бюджет — так прорахунок буде точним",
    hasSiteLabel: "Чи є у вас сайт зараз",
    hasSitePlaceholder: "Оберіть",
    siteUrlLabel: "Адреса сайту",
    siteUrlPlaceholder: "https://…",
    descriptionLabel: "Коментар",
    descriptionPlaceholder: "Що зараз не працює, які сторінки потрібні, дедлайн (необовʼязково)",
    configLabel: "Конфігурація з калькулятора",
    showDetails: "Додати коментар",
    hideDetails: "Сховати коментар",
    detailsMeta: "необовʼязково",
    submit: "Отримати безкоштовний прорахунок",
    submitDemo: "Отримати тестовий доступ",
    successTitle: "Дякуємо!",
    successBody: "Відповімо протягом 24 годин у робочий час.",
    successOrTg: "Написати в Telegram зараз",
    errorBody: "Щось пішло не так. Спробуйте ще раз або пишіть в Telegram",
    privacy:
      "Не передаємо ваші дані третім особам. Зберігаємо тільки для відповіді на вашу заявку.",
    privacyLink: "Політика конфіденційності",
    privacyHref: "/policy",
  },
  en: {
    nameLabel: "Name",
    namePlaceholder: "How should we address you? (optional)",
    namePlaceholderShort: "Optional",
    contactLabel: "Phone, WhatsApp or email",
    contactPlaceholder: "+45..., or hello@example.com",
    contactPlaceholderShort: "Phone, WhatsApp or email",
    contactDescription: "We reply wherever suits you",
    contactValidation: "Please enter a phone, WhatsApp or email",
    tierLabel: "What you need",
    tierPlaceholder: "Choose",
    budgetLabel: "Budget",
    budgetPlaceholder: "Choose a range",
    budgetValidation: "Pick a budget so the quote is accurate",
    hasSiteLabel: "Do you have a website now?",
    hasSitePlaceholder: "Choose",
    siteUrlLabel: "Website address",
    siteUrlPlaceholder: "https://…",
    descriptionLabel: "Comment",
    descriptionPlaceholder: "What isn't working, which pages you need, deadline (optional)",
    configLabel: "Calculator configuration",
    showDetails: "Add a comment",
    hideDetails: "Hide comment",
    detailsMeta: "optional",
    submit: "Get a free quote",
    submitDemo: "Get demo access",
    successTitle: "Thank you!",
    successBody: "We'll reply within 24 hours on business days.",
    successOrTg: "Message us on WhatsApp now",
    errorBody: "Something went wrong. Try again or message us on WhatsApp",
    privacy:
      "We don't share your data with third parties. We only store it to reply to your inquiry.",
    privacyLink: "Privacy Policy",
    privacyHref: "/en/policy",
  },
  ru: {
    nameLabel: "Имя",
    namePlaceholder: "Как к вам обращаться (необязательно)",
    namePlaceholderShort: "Необязательно",
    contactLabel: "Телефон, Telegram или email",
    contactPlaceholder: "+380..., @username или hello@example.com",
    contactPlaceholderShort: "+380..., @username или email",
    contactDescription: "Ответим туда, где вам удобно",
    contactValidation: "Укажите телефон, Telegram или email",
    tierLabel: "Что нужно",
    tierPlaceholder: "Выберите",
    budgetLabel: "Бюджет",
    budgetPlaceholder: "Выберите диапазон",
    budgetValidation: "Выберите бюджет — так расчёт будет точным",
    hasSiteLabel: "Есть ли у вас сайт сейчас",
    hasSitePlaceholder: "Выберите",
    siteUrlLabel: "Адрес сайта",
    siteUrlPlaceholder: "https://…",
    descriptionLabel: "Комментарий",
    descriptionPlaceholder: "Что сейчас не работает, какие страницы нужны, дедлайн (необязательно)",
    configLabel: "Конфигурация из калькулятора",
    showDetails: "Добавить комментарий",
    hideDetails: "Скрыть комментарий",
    detailsMeta: "необязательно",
    submit: "Получить бесплатный расчёт",
    submitDemo: "Получить тестовый доступ",
    successTitle: "Спасибо!",
    successBody: "Ответим в течение 24 часов в рабочее время.",
    successOrTg: "Написать в Telegram сейчас",
    errorBody: "Что-то пошло не так. Попробуйте ещё раз или пишите в Telegram",
    privacy:
      "Не передаём ваши данные третьим лицам. Храним только для ответа на вашу заявку.",
    privacyLink: "Политика конфиденциальности",
    privacyHref: "/policy",
  },
} as const satisfies Record<LeadFormLocale, Record<string, string>>;
